services:
  jinya_gallery.components.schema_tool:
      public: true
      class: HelperBundle\Components\Database\SchemaTool
      arguments:
        - '@doctrine.orm.entity_manager'
  jinya_gallery.components.asset_dumper:
      class: HelperBundle\Components\AssetDumper
      arguments:
        - '@assetic.asset_manager'
        - '%assetic.variables%'
        - '%assetic.write_to%'
  jinya_gallery.components.datatables_request_parser:
      class: HelperBundle\Components\DataTables\DatatablesRequestParser
  jinya_gallery.components.form_generator:
      class: HelperBundle\Components\Form\FormGenerator
      arguments:
        - '@form.factory'
        - '@jinya_gallery.services.theme_service'

  jinya_gallery.monolog.my_sql_handler:
      class: HelperBundle\Logging\MySqlHandler
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@monolog.logger.logging'
  jinya_gallery.monolog.access_log_handler:
      class: HelperBundle\Logging\AccessLogHandler
      arguments:
        - '@doctrine.orm.entity_manager'
  jinya_gallery.monolog.request_processor:
      class: HelperBundle\EventSubscriber\Monolog\RequestProcessor
      arguments:
        - '@request_stack'
      tags:
        - { name: monolog.processor, method: processRecord, handler: accesslog }

  jinya_gallery.event_subscriber.request_event_subscriber:
      class: HelperBundle\EventSubscriber\RequestEventSubscriber
      arguments:
        - '%kernel.root_dir%'
        - '@router.default'
      tags:
          - { name: kernel.event_subscriber }
  jinya_gallery.event_subscriber.kernel_exception_subscriber:
      class: HelperBundle\EventSubscriber\KernelExceptionSubscriber
      arguments:
        - '@router.default'
        - '@logger'
      tags:
          - { name: kernel.event_subscriber }

  twig_extensions.intl:
    class: Twig_Extensions_Extension_Intl
    tags:
      - { name: twig.extension }

  jinya_gallery.commands.compile_themes_command:
      class: HelperBundle\Command\CompileThemesCommand
      arguments:
        - '@jinya_gallery.services.theme_service'
        - '@jinya_gallery.services.theme_compiler_service'
      calls:
          - [setContainer, ['@service_container']]
      tags:
          - { name: console.command }