services:
  jinya_gallery.services.log_service:
      class: HelperBundle\Services\Log\LogService
      arguments:
        - '@doctrine.orm.entity_manager'
  jinya_gallery.services.access_log_service:
      class: HelperBundle\Services\Log\AccessLogService
      arguments:
        - '@doctrine.orm.entity_manager'

  jinya_gallery.services.schema_tool:
      public: true
      class: HelperBundle\Services\Database\SchemaTool
      arguments:
        - '@doctrine.orm.entity_manager'
  jinya_gallery.components.asset_dumper:
      class: HelperBundle\Components\AssetDumper
      arguments:
        - '@assetic.asset_manager'
        - '%assetic.variables%'
        - '%assetic.write_to%'
  jinya_gallery.monolog.my_sql_handler:
      class: HelperBundle\Logging\MySqlHandler
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@monolog.logger.logging'
  jinya_gallery.monolog.access_log_handler:
      class: HelperBundle\Logging\AccessLogHandler
      arguments:
        - '@doctrine.orm.entity_manager'

  jinya_gallery.event_subscriber.request_event_subscriber:
      class: HelperBundle\EventSubscriber\RequestEventSubscriber
      arguments:
        - '%kernel.root_dir%'
        - '@router.default'
      tags:
          - { name: kernel.event_subscriber }

  jinya_gallery.monolog.request_processor:
      class: HelperBundle\EventSubscriber\Monolog\RequestProcessor
      arguments:
        - '@request_stack'
      tags:
        - { name: monolog.processor, method: processRecord, handler: accesslog }

  twig_extensions.intl:
    class: Twig_Extensions_Extension_Intl
    tags:
      - { name: twig.extension }