parameters:
  mailer_sender: '%env(MAILER_SENDER)%'
  jinya_version: 6.1.4
  jinya_gallery.temp_dir: '%kernel.project_dir%/var/tmp'
  jinya_gallery.profiler.out_dir: '%kernel.project_dir%/var/profiler'
  jinya_gallery.theme.directory: themes

jinya_profiling:
  profiler:
    out_dir: '%jinya_gallery.profiler.out_dir%'