monolog:
    channels: ['logging']
    handlers:
        db:
            type: service
            id: Jinya\Logging\MySqlHandler
            channels: ['!doctrine', '!logging']
        accesslog:
            type: service
            id: Jinya\Logging\AccessLogHandler
            channels: ['request']