security:
  role_hierarchy:
    ROLE_SUPER_ADMIN: ROLE_ADMIN

  providers:
    in_memory: { memory: ~ }

  firewalls:
    backend:
      pattern: ^/
      form_login:
        provider: in_memory
        login_path: backend_login_route
        csrf_token_generator: security.csrf.token_manager
        default_target_path: /backend/
        always_use_default_target_path: false

      logout: true
      anonymous: true
    designer:
      pattern: ^/
      form_login:
        login_path: backend_login_route
        provider: in_memory
        csrf_token_generator: security.csrf.token_manager
        default_target_path: /designer/
        always_use_default_target_path: false

      logout: true
      anonymous: true
  access_control:
    - { path: ^/backend/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/backend/fos/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/backend/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/backend/, role: IS_AUTHENTICATED_FULLY }
    - { path: ^/designer/, role: ROLE_WRITER }