security:
  role_hierarchy:
    ROLE_SUPER_ADMIN: ROLE_ADMIN
    ROLE_ADMIN: ROLE_WRITER

  access_decision_manager:
    strategy: consensus
    allow_if_all_abstain: false
    allow_if_equal_granted_denied: false

  encoders:
    Jinya\Entity\User:
      algorithm: bcrypt

  providers:
    jinya_db_provider:
      entity:
        class: Jinya\Entity\User
        property: email

  firewalls:
    api:
      pattern: ^/
      http_basic:
        provider: jinya_db_provider

      logout: true
      anonymous: true
    designer:
      pattern: ^/
      form_login:
        login_path: jinya_account_login
        check_path: jinya_account_login
        provider: jinya_db_provider
        csrf_token_generator: security.csrf.token_manager
        default_target_path: /designer/
        always_use_default_target_path: false

      logout: true
      anonymous: true
  access_control:
    - { path: ^/account/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/designer/, roles: ROLE_WRITER }
    - { path: ^/api/, roles: IS_AUTHENTICATED_ANONYMOUSLY }