twig:
    paths:
      - '%kernel.project_dir%/templates'
      - '%kernel.project_dir%/themes': Theme
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
      ajax: false
