twig:
    paths:
      '%kernel.project_dir%/templates/bundles/InstallBundle': Jinya_Install
      '%kernel.project_dir%/templates': Jinya
      '%kernel.project_dir%/themes': Theme
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
      ajax: false
