install_index:
    controller: Jinya\Controller\InstallController::indexAction
    path: /install
install_admin:
    controller: Jinya\Controller\InstallController::createAdminAction
    path: /install/admin
install_database:
    controller: Jinya\Controller\InstallController::createDatabaseAction
    path: /install/database
install_done:
    controller: Jinya\Controller\InstallController::doneAction
    path: /install/done
jinya:
    resource: "../src/Controller/"
    type: annotation
    prefix: /