jinya:
    resource: "../src/Controller/"
    type: annotation
    prefix: /

designer:
    resource: "../src/Controller/Designer"
    type: annotation
    prefix: /designer

backend:
    resource: "../src/Controller/Backend"
    type: annotation
    prefix: /backend

frontend:
    resource: "../src/Controller/Frontend"
    type: annotation
    prefix: /frontend