designer:
    resource: "../src/Controller/Designer"
    type: annotation
    prefix: /designer

jinya:
    resource: "../src/Controller/"
    type: annotation
    prefix: /

backend:
    resource: "../src/Controller/Backend"
    type: annotation
    prefix: /backend