designer:
    resource: "../src/Controller/Designer"
    type:     annotation
    prefix:   /designer

install:
    resource: "../src/Controller/Install"
    type: annotation
    prefix: /install

frontend:
    resource: "../src/Controller/Frontend"
    type:     annotation
    prefix:   /