parameters:
    database_host: 127.0.0.1
    database_port: 3306
    database_name: jinya-gallery-cms
    database_user: root
    database_password: root
    secret: 59fcf05f29ee9
    mailer_transport: smtp
    mailer_host: localhost
    mailer_port: 1025
    mailer_user: root
    mailer_password: root
