parameters:
    database_host: localhost
    database_port: 3306
    database_name: jinya-gallery-cms
    database_user: root
    database_password: start
    secret: 5a01ee9c3b46b
    mailer_transport: smtp
    mailer_host: localhost
    mailer_port: 25
    mailer_user: start@jinya.com
    mailer_password: start
    base_url: http://localhost:8000/
