parameters:
    database_host: localhost
    database_port: 3306
    database_name: jinya-gallery
    database_user: root
    database_password: start
    secret: 59faf7cd53dcb
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: start
    mailer_password: start
