# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
  encoders:
    FOS\UserBundle\Model\UserInterface: bcrypt

  role_hierarchy:
    ROLE_SUPER_ADMIN: ROLE_ADMIN

  providers:
    fos_userbundle:
      id: fos_user.user_provider.username_email

  firewalls:
    backend:
      pattern: ^/
      form_login:
        login_path: backend_login_route
        check_path: fos_user_security_check
        provider: fos_userbundle
        csrf_token_generator: security.csrf.token_manager
        default_target_path: /backend/
        always_use_default_target_path: false

      logout: true
      anonymous: true
  access_control:
    - { path: ^/backend/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/backend/fos/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/backend/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/backend/, role: IS_AUTHENTICATED_FULLY }