services:
  Symfony\Component\HttpKernel\Profiler\Profiler:

  Symfony\Component\HttpKernel\Profiler\ProfilerStorageInterface:
    class: Symfony\Component\HttpKernel\Profiler\FileProfilerStorage
    arguments:
      $dsn: '%profiler.storage.dsn%'