---
- name: Link encore service
  file:
    path: /etc/init.d/encore
    src: /vagrant/vagrant-files/roles/encore/files/service.sh
    state: link
    mode: o=rwx,g=x,u=x
  become: yes
- name: Create and start encore service
  service:
    state: started
    name: encore
    enabled: yes
  become: yes