---
- name: Install rsync, inotify and utilities
  yum:
    name:
      - rsync
      - inotify-tools
      - git
      - vim
  become: true
- name: Update SELinux
  selinux:
    policy: targeted
    state: permissive
  become: true