parameters:
    locale: 'de'
    jinya_gallery.theme.directory: themes

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false
    Jinya\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Test,Kernel.php}'

    Jinya\Controllers:
        resource: '../src/*'
        tags: ['controller.service_arguments']