services:
  _defaults:
      # automatically injects dependencies in your services
      autowire: true
      # automatically registers your services as commands, event subscribers, etc.
      autoconfigure: true
      # this means you cannot fetch services directly from the container via $container->get()
      # if you need to do this, you can override this setting on individual services
      public: true
  jinya_gallery.services.user_service:
      class: Jinya\Services\Users\UserService
      arguments:
        - '@fos_user.user_manager'
        - '@doctrine.orm.entity_manager'
        - '@fos_user.util.user_manipulator'
        - '@jinya_gallery.services_media.media_service'

  jinya_gallery.services.gallery_service:
      class: Jinya\Services\Galleries\GalleryService
      arguments:
        - '@doctrine.orm.default_entity_manager'
        - '@jinya_gallery.services_media.media_service'
        - '@jinya_gallery.services_slug.slug_service'
        - '@jinya_gallery.services.label_service'

  jinya_gallery.services.artwork_service:
      class: Jinya\Services\Artworks\ArtworkService
      arguments:
        - '@doctrine.orm.default_entity_manager'
        - '@jinya_gallery.services_media.media_service'
        - '@jinya_gallery.services_slug.slug_service'
        - '@jinya_gallery.services.label_service'

  jinya_gallery.services.artwork_position_service:
      class: Jinya\Services\Artworks\ArtworkPositionService
      arguments:
        - '@jinya_gallery.services.gallery_service'
        - '@jinya_gallery.services.artwork_service'
        - '@doctrine.orm.default_entity_manager'

  jinya_gallery.services.page_service:
      class: Jinya\Services\Pages\PageService
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@jinya_gallery.services_slug.slug_service'

  jinya_gallery.services.form_service:
      class: Jinya\Services\Form\FormService
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@jinya_gallery.services_slug.slug_service'

  jinya_gallery.services.menu_service:
      class: Jinya\Services\Menu\MenuService
      arguments:
        - '@doctrine.orm.entity_manager'

  jinya_gallery.services_routing.route_retrieval_service:
      class: Jinya\Services\Routing\RouteRetrievalService
      arguments:
        - '@jinya_gallery.services.page_service'
        - '@jinya_gallery.services.form_service'
        - '@jinya_gallery.services.gallery_service'
        - '@jinya_gallery.services.artwork_service'
        - '@router'
  jinya_gallery.services.route_service:
      class: Jinya\Services\Routing\RouteService
      arguments:
        - '@doctrine.orm.entity_manager'

  jinya_gallery.services.theme_service:
      class: Jinya\Services\Theme\ThemeService
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@jinya_gallery.services.frontend_configuration_service'
        - '@twig.loader'
        - '@jiyna_gallery.services.theme_config_service'
      lazy: true
  jiyna_gallery.services.theme_config_service:
      class: Jinya\Services\Theme\ThemeConfigService
      arguments:
        - '@jinya_gallery.services.theme_service'
        - '@jinya_gallery.services.menu_service'
        - '@doctrine.orm.entity_manager'
        - '%jinya_gallery.theme.directory%'
        - '%kernel.project_dir%'
  jinya_gallery.services.theme_compiler_service:
      class: Jinya\Services\Theme\ThemeCompilerService
      arguments:
        - '@jiyna_gallery.services.theme_config_service'
        - '@jinya_gallery.services.scss_compiler_service'
        - '%kernel.project_dir%'
  jinya_gallery.services.theme_sync_service:
      class: Jinya\Services\Theme\ThemeSyncService
      arguments:
        - '@jinya_gallery.services.theme_service'
        - '@doctrine.orm.entity_manager'
        - '%kernel.project_dir%'
        - '%jinya_gallery.theme.directory%'

  jinya_gallery.services.frontend_configuration_service:
      class: Jinya\Services\Configuration\FrontendConfigurationService
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@jinya_gallery.services.theme_service'
      lazy: true

  jinya_gallery.services.label_service:
      class: Jinya\Services\Labels\LabelService
      arguments:
        - '@doctrine.orm.entity_manager'

  jinya_gallery.services.log_service:
      class: Jinya\Services\Log\LogService
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@logger'

  jinya_gallery.services.access_log_service:
      class: Jinya\Services\Log\AccessLogService
      arguments:
        - '@doctrine.orm.entity_manager'

  jinya_gallery.services_slug.slug_service:
      class: Jinya\Services\Slug\SlugService

  jinya_gallery.services_media.media_service:
      class: Jinya\Services\Media\MediaService
      arguments:
        - '%base_url%'
        - '%kernel.root_dir%'

  jinya_gallery.services.mailer_service:
      class: Jinya\Services\Mailing\MailerService
      arguments:
        - '@mailer'
        - '%mailer_sender%'

  jinya_gallery.services.scss_compiler_service:
      class: Jinya\Services\Scss\ScssCompilerService