services:
  _defaults:
      # automatically injects dependencies in your services
      autowire: true
      # automatically registers your services as commands, event subscribers, etc.
      autoconfigure: true
      # this means you cannot fetch services directly from the container via $container->get()
      # if you need to do this, you can override this setting on individual services
      public: false
  jinya_gallery.services.gallery_service:
      class: ServiceBundle\Services\Galleries\GalleryService
      arguments:
        - '@doctrine.orm.default_entity_manager'
        - '@jinya_gallery.services_media.media_service'
        - '@jinya_gallery.services_slug.slug_service'
        - '@jinya_gallery.services.label_service'
  jinya_gallery.services.artwork_service:
      class: ServiceBundle\Services\Artworks\ArtworkService
      arguments:
        - '@doctrine.orm.default_entity_manager'
        - '@jinya_gallery.services_media.media_service'
        - '@jinya_gallery.services_slug.slug_service'
        - '@jinya_gallery.services.label_service'
  jinya_gallery.services.artwork_position_service:
      class: ServiceBundle\Services\Artworks\ArtworkPositionService
      arguments:
        - '@jinya_gallery.services.gallery_service'
        - '@jinya_gallery.services.artwork_service'
        - '@doctrine.orm.default_entity_manager'
  jinya_gallery.services.page_service:
      class: ServiceBundle\Services\Pages\PageService
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@jinya_gallery.services_slug.slug_service'
  jinya_gallery.services.form_service:
      class: ServiceBundle\Services\Form\FormService
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@jinya_gallery.services_slug.slug_service'
  jinya_gallery.services.menu_service:
      class: ServiceBundle\Services\Menu\MenuService
      arguments:
        - '@doctrine.orm.entity_manager'
  jinya_gallery.services.route_service:
      class: ServiceBundle\Services\Routing\RouteService
      arguments:
        - '@doctrine.orm.entity_manager'
  jinya_gallery.services.theme_service:
      class: ServiceBundle\Services\Theme\ThemeService
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@jinya_gallery.services.frontend_configuration_service'
        - '%jinya_gallery.theme.directory%'
        - '%kernel.project_dir%'
        - '@twig.loader'
        - '@jinya_gallery.services.scss_compiler_service'
        - '@jinya_gallery.services.menu_service'
      lazy: true
  jinya_gallery.services.frontend_configuration_service:
      class: ServiceBundle\Services\Configuration\FrontendConfigurationService
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@jinya_gallery.services.theme_service'
      lazy: true
  jinya_gallery.services.label_service:
      class: ServiceBundle\Services\Labels\LabelService
      arguments:
        - '@doctrine.orm.entity_manager'