---
- name: Download mailhog from Github
  get_url:
    url: https://github.com/mailhog/MailHog/releases/download/v1.0.0/MailHog_linux_amd64
    dest: /usr/local/bin/mailhog
    mode: o=rwx,g=rwx,u=x
  become: yes
- name: Link mailhog service
  file:
    src: /vagrant/vagrant-files/roles/mailhog/files/service.sh
    path: /etc/init.d/mailhog
    state: link
  become: yes
- name: Create and start mailhog service
  service:
    state: started
    name: mailhog
    enabled: yes
  become: yes