imports:
    - { resource: ../../../../app/config/parameters.yml }
fos_user:
    db_driver: orm
    firewall_name: backend
    user_class: DataBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
assetic:
  debug: '%kernel.debug%'
  use_controller: '%kernel.debug%'
  assets:
    backendcss:
      inputs:
        - '@BackendBundle/Resources/public/scss/jinya-gallery.scss'
    backendjs:
      inputs:
        - '@BackendBundle/Resources/public/typescript/backend/layout/Loader.js'
        - '@BackendBundle/Resources/public/typescript/backend/layout/NavigationSwitcher.js'
        - '@BackendBundle/Resources/public/typescript/backend/layout/TableElementSelector.js'
        - '@BackendBundle/Resources/public/typescript/backend/layout/AjaxExecutor.js'
        - '@BackendBundle/Resources/public/typescript/backend/layout/DatatablesActivator.js'
        - '@BackendBundle/Resources/public/typescript/backend/layout/Searcher.js'
    backend_galleries_overview_js:
      inputs:
        - '@BackendBundle/Resources/public/typescript/backend/galleries/OverviewViewModel.js'
        - '@BackendBundle/Resources/public/typescript/backend/galleries/Overview.js'
  filters:
      jsqueeze: ~
      scssphp:
          formatter: 'Leafo\ScssPhp\Formatter\Compressed'