services:
#    backend.example:
#        class: BackendBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  jinya_gallery.twig_extension.controller_utils:
      class: BackendBundle\Twig\Extension\ControllerUtils
      tags:
          - { name: twig.extension }
  jinya_gallery.twig_extension.translation_utils:
      class: BackendBundle\Twig\Extension\TranslationUtils
      arguments:
        - '@translator.default'
      tags:
          - { name: twig.extension }