services:
#    backend.example:
#        class: BackendBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  jinya_gallery.services.user_service:
      public: true
      class: BackendBundle\Service\Users\UserService
      arguments:
        - '@fos_user.user_manager'
        - '@doctrine.orm.entity_manager'
        - '@fos_user.util.user_manipulator'
        - '@kernel'

  jinya_gallery.services.schema_tool:
      public: true
      class: BackendBundle\Service\Database\SchemaTool
      arguments:
        - '@doctrine.orm.entity_manager'

  backend.twig_extension.controller_utils:
      class: BackendBundle\Twig\Extension\ControllerUtils
      tags:
          - { name: twig.extension }