services:
#    backend.example:
#        class: BackendBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  jinya_gallery.service_user.user_creator:
      class: BackendBundle\Service\Users\UserCreator
      arguments: ['@fos_user.user_manager']
  backend.twig_extension.controller_utils:
      class: BackendBundle\Twig\Extension\ControllerUtils
      tags:
          - { name: twig.extension }